name: pushspec

on:
  push:
    branches:
      - releaser

jobs:
  pushspec:
    name: Merge multiple spec files into one.
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Merge spec files
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - run: npm install -g swagger-cli
      - run: make spec

