name: pushspec

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.[0-9]+
      - feature/*

jobs:
  mergespec:
    name: Bundle spec files and validate it.
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install -g swagger-cli
      - run: make spec

      - name: Save build artifact
        uses: actions/upload-artifact@v1
        with:
          node-version: ${{matrix.node-version}}
          name: build
          path: build/openapi.yml
 
  pushspec:
    name: Upload generated OpenAPI description
    runs-on: ubuntu-latest
    needs: mergespec

    steps:
      - uses: actions/checkout@v2
      - name: set output for versioning
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Download the spec file
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Upload spec file to swaggerhub
        env:
          AUTH_TOKEN: ${{secrets.SGH_TOKEN}}
          RELEASE_VERSION: ${{steps.vars.outputs.tag}}
        shell: bash
        run: |
          version=${RELEASE_VERSION}
          version=`echo $version|sed 's#[^a-zA-Z0-9_\.\-]#_#g'`
          echo "Uploading OpenAPI spec v ${RELEASE_VERSION}"
          def=`cat build/openapi.yml`
          curl -d "$def" "https://api.swaggerhub.com/apis/idoko/moira-alert/?isPrivate=false&version=${version}&oas=3.0.0&force=true" -H "content-type: application/yaml" -H "Authorization: ${AUTH_TOKEN}"



