name: pushspec

on:
  push:
    branches:
      - master

jobs:
  mergespec:
    name: Bundle spec files and validate it.
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bundle spec files
        uses: actions/upload-artifact@v1
        with:
          node-version: ${{matrix.node-version}}
          name: specfile
          path: build/openapi.yml
      - run: npm install -g swagger-cli && make spec
 
  pushspec:
    name: Upload generated OpenAPI description
    runs-on: ubuntu-latest
    needs: mergespec

    steps:
      - name: Download the spec file
        uses: actions/download-artifact@v1
        with:
          name: specfile
      - name: Upload spec file to swaggerhub
        env:
          AUTH_TOKEN: ${{secrets.SGH_TOKEN}}
        shell: bash
        run: |
          version=3.11
          def=`cat build/openapi.yml`
          curl -d "$definition" "https://api.swaggerhub.com/apis/idoko/moira-alert/?isPrivate=false&version$version&force=false" -H "content-type: application/yaml" -H "Authorization: ${AUTH_TOKEN}"



